### ISSUE TITLE
tBTC. Step 2/5. Error initiating deposit.

### ISSUE THREAD

**Issue by Gregg-First** [keep-network/tbtc-dapp#229] opened 2020-07-10 18:09 UTC
### Description:
An error occurred on step 2 of minting tBTC.
### Expected behavior: 
Receiving an address where to send testBTC.
### Environment details:
OS: Windows 10 pro, version 10.0.18362, 64 bit OS
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), 7.7.9
### Error messege
Step 2/5
Error initiating deposit
Initiating...
Transaction has been reverted by the EVM: { "blockHash": "0x021961f180ea6bb7b99f3548323010951b35ff46746c034db4536bb4e1750311", "blockNumber": 8267520, "contractAddress": null, "cumulativeGasUsed": 660263, "from": "0x7a526a1dc3d04683d6e04a5b304bb80efe724dce", "gasUsed": 660263, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0x5536a33ed2d7e055f7f380a78ae9187a3b1d8f75", "transactionHash": "0xe20799ba94b24b7a2e75593d4d00a776072b0109d8242199525be0ec143c067a", "transactionIndex": 0, "events": {} }

### Log:

inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at u (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at a (inpage.js:1)
inpage.js:1 MetaMask - RPC Error: The method undefined does not exist/is not available Object
(anonymous) @ inpage.js:1
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at u (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at a (inpage.js:1)
inpage.js:1 MetaMask - RPC Error: The method undefined does not exist/is not available Object
(anonymous) @ inpage.js:1
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at u (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at a (inpage.js:1)
inpage.js:1 MetaMask - RPC Error: The method undefined does not exist/is not available Object
(anonymous) @ inpage.js:1
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at u (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at a (inpage.js:1)
inpage.js:1 MetaMask - RPC Error: gas required exceeds allowance (8000029) or always failing transaction Object
(anonymous) @ inpage.js:1
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://iplppiggblloelhoglpmkmbinggcaaoc/app/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by Gregg-First** [comment] 2020-07-10 18:11
https://ropsten.etherscan.io/tx/0xe20799ba94b24b7a2e75593d4d00a776072b0109d8242199525be0ec143c067a

**Comment by suprnrdy** [comment] 2020-07-10 18:33
When starting step two and clicking 'Begin', there is an exception thrown in the contract code in MetaMask. 
<img width="1598" alt="Screen Shot 2020-07-10 at 11 27 39 AM" src="https://user-images.githubusercontent.com/1414501/87186744-de65f080-c2a0-11ea-95ee-4773602dcd0a.png">

If attempting to sign and proceed, you'll get an error with status: "Not enough operators in pool", which can be seen here: https://ropsten.etherscan.io/tx/0xec4a449a622cd153ed95f82a789f44ea2f241a928a9e45fb6a667570aa70fca7

tBTC dApp will error out with the following error:
`Transaction has been reverted by the EVM: { "blockHash": "0xb1e786f5caf1dd2ed2d9fc8a733a5ca93314b272ec31c94c5a47c9dbe90d8f4c", "blockNumber": 8267656, "contractAddress": null, "cumulativeGasUsed": 535184, "from": "0x426b70cde4ac1da2d4ab3167c001c07d2e8b3448", "gasUsed": 535184, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0x5536a33ed2d7e055f7f380a78ae9187a3b1d8f75", "transactionHash": "0xec4a449a622cd153ed95f82a789f44ea2f241a928a9e45fb6a667570aa70fca7", "transactionIndex": 0, "events": {} }`

**Comment by VVyvrn** [comment] 2020-07-11 03:47
I believe I am experiencing the same issues, using Metamask in Brave browser on macOS.

Transaction hash shows: Fail with error 'Not enough operators in pool'

https://ropsten.etherscan.io/tx/0x256d39304d329ab772b97b216ac5ae1909fc264fa76bbd6b67f40f20abc82f35

Log:

Error initiating deposit
Initiating...
Transaction has been reverted by the EVM: { "blockHash": "0x46cc9ae8f7d6ceb1e16cc2a7e6218111001b28335c83a17e4370c49d58d9cf43", "blockNumber": 8270148, "contractAddress": null, "cumulativeGasUsed": 556099, "from": "0x9a954affda009687abbef135306d9015e63835ec", "gasUsed": 535099, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0x5536a33ed2d7e055f7f380a78ae9187a3b1d8f75", "transactionHash": "0x256d39304d329ab772b97b216ac5ae1909fc264fa76bbd6b67f40f20abc82f35", "transactionIndex": 1, "events": {} }


inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
inpage.js:1 MetaMask - RPC Error: 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>403 Forbidden</title>
  </head>
  <body>
    <h1>Error 403 Forbidden</h1>
    <p>Forbidden</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-dfw18624-DFW 1594438342 2800098887</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
 Object
(anonymous) @ inpage.js:1
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
inpage.js:1 MetaMask - RPC Error: 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>403 Forbidden</title>
  </head>
  <body>
    <h1>Error 403 Forbidden</h1>
    <p>Forbidden</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-dfw18624-DFW 1594438342 2800098887</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
 Object
(anonymous) @ inpage.js:1
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
inpage.js:1 MetaMask - RPC Error: 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>403 Forbidden</title>
  </head>
  <body>
    <h1>Error 403 Forbidden</h1>
    <p>Forbidden</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-dfw18624-DFW 1594438342 2800098887</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
 Object
(anonymous) @ inpage.js:1
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
inpage.js:1 MetaMask - RPC Error: gas required exceeds allowance (8000029) or always failing transaction Object
(anonymous) @ inpage.js:1
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by VinnyR** [comment] 2020-07-11 03:48
Hello, I can confirm I am seeing the same issue:

### Description:

On step 2 of the TBTC minting process, straight after clicking confim in metamask (for the first time in the process), the dapp web page shows:

Step 2/5 Error initiating deposit

`Transaction has been reverted by the EVM: { "blockHash": "0xfc27c560bb6922c8ffd2a45b6ffac22871f05f432863cc96030c0668a7992bd3", "blockNumber": 8270134, "contractAddress": null, "cumulativeGasUsed": 535099, "from": "0x26dfe5bdf93679e953c876a4fbec2a99d399f648", "gasUsed": 535099, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0x5536a33ed2d7e055f7f380a78ae9187a3b1d8f75", "transactionHash": "0x2b1d12df142d25f651f088dfae0df9fcbdfca8549508a60fa9681810d0127e2b", "transactionIndex": 0, "events": {} }`


There are no new logs in the console since the previous step, but the log file is attached below nevertheless.

### Steps to reproduce the behavior:

1. Go to dapp.test.tbtc.network
2. Click deposit (takes you to dapp.test.tbtc.network/deposit)
3. Click ‘connect to a Wallet’ button, click metamask, login to metamask
4. Click ‘Connect’ in metamask (when it says “tBTC would like to connect to your account”)
5. On the web page (Step 1/5 - Initiate a deposit), click ‘Begin now’
6. Metamask window now appears, asking to confirm contract interaction (and webpage proceeds to step 2/5 initiating deposit). (error message appears in metamask ALERT: Transaction Error. Exception thrown in contract code). Click confirm in metamask
7. After a abotu 15 seconds, the error message above appears on the dapp web page.


### Expected behavior:

Web page should have proceeded to step 3/5.

### Environment details:

OS: Windows 10 Pro, Version 1909, build 18363.900, 64 bit OS
CPU: x64 based
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), Version 7.7.9

### Additional context:
console log file: 
[dapp.test.tbtc.network-1594439241122.log](https://github.com/keep-network/tbtc-dapp/files/4906235/dapp.test.tbtc.network-1594439241122.log)

**Comment by VinnyR** [comment] 2020-07-13 02:00
I can further confirm that I get the sam error message in this environment too:

OS: Windows Ubuntu 18.04.2 LTS 64-bit
Web Browser: Mozilla Firefox 78.0.1 (64-bit)
Wallet: Metamask (Firefox addon), Version 8.0.4

**Comment by saltypalo** [comment] 2020-07-13 08:25
Confirming that I get the same error in this environment too:

OS: Windows 10 Home, version 10.0.18362, 64 bit OS
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), 7.7.9

**Comment by AJolly** [comment] 2020-07-13 22:51
Same.

Transaction has been reverted by the EVM: { "blockHash": "0xf6da87ebfb754708cdda769414b8391ad3d6f40d2c73decb3d74cb03edb26bef", "blockNumber": 8288388, "contractAddress": null, "cumulativeGasUsed": 1729514, "from": "0xae6a1f271885419f5aa29a90d396e8195d82bb85", "gasUsed": 1729514, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0x5536a33ed2d7e055f7f380a78ae9187a3b1d8f75", "transactionHash": "0x52dd437d133850f848f5de3d3172dc777a7430e9d8466a0c689eea46855e68df", "transactionIndex": 0, "events": {} }

**Comment by Shadowfiend** [comment] 2020-07-24 22:14
These transactions were all symptoms of the problems described in [this comment](https://github.com/keep-network/tbtc-dapp/issues/258#issuecomment-663536507). Closing this issue, since we've since handled that problem. Thanks for the reports!

**Closed by Shadowfiend** 2020-07-24 22:14 UTC
Labels: 👩‍⚕️triage
