### ISSUE TITLE
Minting costs for 1 TBTC and 0.001 TBTC is the same. It doesn't make sense.

### ISSUE THREAD

**Issue by jasonchewyl** [keep-network/tbtc-dapp#296] opened 2020-07-24 17:52 UTC
![image](https://user-images.githubusercontent.com/53902721/88420215-221c3680-ce19-11ea-9ecf-f8a0b589c4c1.png)

![image](https://user-images.githubusercontent.com/53902721/88420222-25afbd80-ce19-11ea-979b-30f626fa5f96.png)

![image](https://user-images.githubusercontent.com/53902721/88420231-28aaae00-ce19-11ea-96d9-1f1328bdb8c9.png)

![image](https://user-images.githubusercontent.com/53902721/88420241-2c3e3500-ce19-11ea-9da8-6320a0633886.png)

![image](https://user-images.githubusercontent.com/53902721/88420257-306a5280-ce19-11ea-9d49-9b4f8d7d8fc8.png)

![image](https://user-images.githubusercontent.com/53902721/88420264-33654300-ce19-11ea-9bd7-3a91667761cb.png)

From the screenshots above, you can see irregardless whether I am minting 0.001 BTC or 0.01 BTC or 0.1 BTC or 1 BTC... the cost to mint TBTC is the same. In this example, **0.689 ETH [gas fee (0.6 ETH) + minting fee (0.074) ETH]**. 

At present ETH prices, this means the cost to mint 
1 BTC = $9,500   $170 **(1.7%)**
0.1 BTC = $950   $170 **(17%)**
0.01 BTC = $95   $170 **(lose money)**

Is it supposed to be like this? It should not be right?

**Comment by Shadowfiend** [comment] 2020-07-24 18:06
Thanks for the detailed issue! It is supposed to be like this, yes. The cost of opening a deposit is fixed based on the cost of setting up the signer group; it is a system cost, and the proceeds are used by the system to supply randomness guarantees around the chosen signers. The signer fee, which is paid to the signers themselves when a deposit is redeemed for BTC, is based on the lot size.

Due to the high cost of gas (and transaction fees on Bitcoin), small lot sizes are more useful for testing than anything else right now. See @mhluongo's note [here](https://github.com/keep-network/tbtc-dapp/issues/293#issuecomment-663328570) on this as well, and the containing issue for a suggestion on how we might make these tradeoffs apparent in the UI.

Closing this for now, since things are working as intended.

**Closed by Shadowfiend** 2020-07-24 18:06 UTC
