### ISSUE TITLE
dApp sends TDT before depositing testnet Bitcoin

### ISSUE THREAD

**Issue by JaviAnibarro** [keep-network/tbtc-dapp#291] opened 2020-07-23 20:44 UTC
### Description:
A clear and concise description of what the bug is and where it appeared e.g. did it appear in the browser or in wallet (e.g. MetaMask). If the bug was in the browser, what was url at that point.

### Environment details:
OS: Windows 10 Pro, Version 1909, build 18363.900, 64 bit OS  
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)  
Wallet: Metamask (Chrome extension), Version 7.7.9

### Screenshots
If applicable, add screenshots to help explain your problem and any console log files.

**Comment by mhluongo** [comment] 2020-07-23 20:44
The is the intended behavior :)

**Comment by mhluongo** [comment] 2020-07-23 20:47
TDTs are called "unqualified" before a BTC deposit has been proven. Once the BTC deposit is proven, a TDT is qualified to mint TBTC.

I think there might be issue here explaining that a TDT is like a deposit "receipt"... or maybe better some sort of "key" to your pending deposit. We've been playing with the right analogy in the UX cc @Gluzman

**Comment by JaviAnibarro** [comment] 2020-07-23 20:49
@mhluongo ops, should I closed it? since it's intended.
I accidentally clicked the post button before finishing the report.

**Comment by mhluongo** [comment] 2020-07-23 20:50
Closing it, but very interested in thoughts on how the purpose of the TDT could be made more obvious!

**Closed by mhluongo** 2020-07-23 20:50 UTC
