### ISSUE TITLE
tBTC Minting step 4/5 - Contract exception error

### ISSUE THREAD

**Issue by chdru** [keep-network/tbtc-dapp#329] opened 2020-08-02 22:40 UTC
### Description:

I'm trying to mint 0.2 tBTC and confirmed that the deposit(tBTC minting) can be allowed as the tBTC minted is 96 out of 100 per contract (https://ropsten.etherscan.io/token/0xa609f2c9c5b7873f353c15d4ef6e151d14db69cc). 
I've sent my 0.2 test BTC and during step 4/5 of tBTC, getting the below error "failed to get merkle proof: [Error: failed to get transaction merkle: [tx 2c941cab41b7d85f3cb717af2ac4f30d30340ee6dbc53ce480d0e91ce0c9e344 not in block at height 1,801,168]] " 
Based on previous experience minting tBTC, trying to reload the page works sometimes but it did even after numerous times this time.

### Steps to reproduce the behavior:
try to mint tBTC using dapp.

### Expected behavior:
Successfully mint tBTC

### Environment details:
OS: Windows 10 
Web Browser: Google Chrome, Version 84.0.4147.105 (Official Build) (64-bit
Wallet: Metamask (Chrome extension), Version 8.0.5

Logs:
[tbtc-dapp-console-log-1596408006761.log](https://github.com/keep-network/tbtc-dapp/files/5013101/tbtc-dapp-console-log-1596408006761.log)

### Screenshots
![image](https://user-images.githubusercontent.com/68074440/89134059-80b37580-d4e7-11ea-88ab-93ccb59ded4a.png)
![image](https://user-images.githubusercontent.com/68074440/89134033-261a1980-d4e7-11ea-8931-13efb2fe0b4e.png)

**Comment by Shadowfiend** [comment] 2020-08-03 13:50
Unfortunately this error is now gone, replaced with `not at current or previous difficulty` which is a common issue on testnet (sadly not one we can really fix; it's a Bitcoin testnet issue).

I'm going to bundle the merkle proof issue with #253, which has the same error, since I expect the root cause will ultimately be the same---though I'm not certain of what it is quite yet. Closing this issue in favor of that one, but please feel free to subscribe to notifications on that one to keep track of progress.

Thank you for the excellent report!

**Closed by Shadowfiend** 2020-08-03 13:50 UTC
