### ISSUE TITLE
Login popup when starting the process

### ISSUE THREAD

**Issue by bonsfi** [keep-network/tbtc-dapp#249] opened 2020-07-13 10:00 UTC
I'm in Ethereum since the early days and have see everything evolve. In my opion tBTC dapp UX lags in the first step because the button "beggin now" is unclickable and the "Connect to a wallet" button is completely in the more far away part of the screen. THIS MAKES THE USER UNRELATE BOTH concepts. Please see the screenshots and comparte with RenProject and Synthetix Mintr.

In my opinion there should be a prompt or more clear call to action to login with Metamask or whatever wallet.
<img width="1018" alt="Screenshot 2020-07-13 at 11 56 11" src="https://user-images.githubusercontent.com/12712595/87291840-3cdcda00-c500-11ea-8bf1-e8b47bf07ae2.png">

Please see the following screenshots:
<img width="1272" alt="Screenshot 2020-07-13 at 11 52 50" src="https://user-images.githubusercontent.com/12712595/87291848-3fd7ca80-c500-11ea-90a7-14ae0fabd6cd.png">
<img width="522" alt="Screenshot 2020-07-13 at 11 57 13" src="https://user-images.githubusercontent.com/12712595/87291854-4108f780-c500-11ea-85ef-8c031812f2d2.png">

**Comment by mhluongo** [comment] 2020-07-19 20:06
You don't need to file two issues on something, even if you feel strongly - it makes more work for the repo maintainers, and splinters discussion around potential improvements.

Closing this as a duplicate of #277.

**Closed by mhluongo** 2020-07-19 20:06 UTC
Labels: enhancement

**Comment by mhluongo** [comment] 2020-07-19 20:07
> splinters discussion around potential improvements.

As an example of this- I think the Mintr UX is a much better approach than Ren's full-page modal, because it displays value to the user before asking for personal information. Unfortunately, I didn't see this screen until finding your dup issue :shrug:
